### ISSUE TITLE
add all pages

### ISSUE THREAD

**Issue by AbdiweliAli** [AbdiweliAli/google-books-tracker#2]

**Comment by AbdiweliAli** [comment]
### Tasks

- [ ] Add home page 
- [ ] Add about page 
- [ ] Add L.Storage page 
- [ ] Add Navigationbar on each page 
- [ ] Should be able to route via Navigationbar
- [ ] 

![Image](https://user-images.githubusercontent.com/114832545/216018708-323badda-92ab-438a-be62-4932a081dfa0.png)
